#ifndef WEAK_COMPILER_FRONTEND_AST_AST_VAR_DECL_HPP
#define WEAK_COMPILER_FRONTEND_AST_AST_VAR_DECL_HPP

// VarDecl(ASTType DataType, <?Symbol representation?>, ASTNode*)

#endif // WEAK_COMPILER_FRONTEND_AST_AST_VAR_DECL_HPP
